const storagedData = {
  project:{
    id:'',
    name:'',
    prefix:'',
    suffix:'',
    updatedAt:'',
    createdAt:'',
    dataFileNum:0,
    resultNum:0
  },
  result:{
    id:'',
    name:'',
    prefix:'',
    suffix:'',
    updatedAt:'',
    createdAt:'',
    dataFileNum:0,
    resultNum:0
  },
  dataFile:{
    id:'',
    name:'',
    prefix:'',
    suffix:'',
    updatedAt:'',
    createdAt:'',
    dataFileNum:0,
    resultNum:0
  },
  package:{
    id:'',
    name:'',
    prefix:'',
    suffix:'',
    updatedAt:'',
    createdAt:'',
    dataFileNum:0,
    resultNum:0
  },
  task:{
    id:'',
    name:'',
    prefix:'',
    suffix:'',
    updatedAt:'',
    createdAt:'',
    dataFileNum:0,
    resultNum:0
  }
}
module.exports = storagedData;